def getBuildDate() {
    def now = new Date()
    def formatter = new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'")
    formatter.timeZone = TimeZone.getTimeZone("UTC")
    return formatter.format(now)
}

pipeline {
    agent any
    environment {
        harborRegistryUrl = 'registry.citglobal.com'
        harborCredentialId = 'registry-citglobal-com'
        repositoryName = 'cit-local-repo/maven-test'
    }
    stages {
        stage('DOCKER_BUILD') {
            steps {
                dir("src/test/pipeline") {
                    script {
                        docker.build("registry.citglobal.com/${repositoryName}:${BUILD_NUMBER}", "--build-arg BUILD_DATE=${getBuildDate()} .")
                    }
                }
            }
        }
        stage('DOCKER_PUSH') {
            steps {
                script {
                    docker.withRegistry("http://${harborRegistryUrl}", harborCredentialId) {
                        docker.image("${harborRegistryUrl}/${repositoryName}:${BUILD_NUMBER}").push()
                        docker.image("${harborRegistryUrl}/${repositoryName}:${BUILD_NUMBER}").push("latest")
                    }
                }
            }
        }
        stage('DOCKER_SCAN') {
            steps {
                script {
                    waitForHarborWebHook fullImageName: "registry.citglobal.com/cit-local-repo/maven-test:latest", server: 'registry.citglobal.com', credentialsId: 'registry-citglobal-com', severity: 'Medium', abortPipeline: false
                    sh "docker rmi ${harborRegistryUrl}/${repositoryName}:${BUILD_NUMBER}"
                }
            }
        }
    }
}
